spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_DATABASE}
      authentication-database: ${DB_AUTH_DATABASE}
server:
  port: ${SERVER_PORT:8090}