spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5433/payment}
    username: ${DB_USERNAME:ashin}
    password: ${DB_PASSWORD:ashin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.ashinsaji.projects.ecommerce.notification.PaymentNotificationRequest
server:
  port: ${SERVER_PORT:8060}
